---
title: "Mini-Project 2"
author: "Kerry LeCure, Libby Leung, Madeleine Hickman"
date: "October 31, 2017"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```
```{r}
#use of full_join via cand_id to join candidates data set with contributions dataset in order to include party affiliation with the data
data <- full_join(candidates, contributions, by = c("cand_id"))
data <- data %>%
  select("cand_party_affiliation", "entity_type") %>% #we determined that these were going to be necessary for what we were looking for
  filter(entity_type == c("CCM", "CAN", "COM", "IND", "ORG", "PAC", "PTY"), !is.na(c("entity_type", "transaction_type", "transaction_amt", "cand_party_affiliation"))) %>% #we filtered the two main parties 
  group_by(cand_party_affiliation) %>%
  count(entity_type)
data
```
```{r}
#function to generalize analysis
party <- function(party_id) {
  data %>%
    filter(cand_party_affiliation == party_id) %>%
    group_by(entity_type) %>%
    summarize(total_entity = n()) %>%
    arrange(desc(total_entity))
}
party(party_id = "DEM")
party(party_id = "REP")

entity <- function(entities) {
  data %>%
    filter(entity_type == entities) %>%
    group_by(cand_party_affiliation) %>%
    summarize(total_party = n()) %>%
    arrange(desc(total_party))
}
entity(entities = "CCM")
```
```{r}
ggplot(data, aes(x = cand_party_affiliation, y = n, fill = entity_type)) +
  geom_bar(stat = "identity", position = "dodge")
```

#blog post explaining
The function `party` sorts the data by `cand_party_affiliation` and shows the amount of times each specific entity (such as an organization or a committee) contributed to a specified party. The function `entities` sorts the data by `entity_type` and will show how many times a each party recieved a contribution from a specified entity.